### PR TITLE
Added Schema for AnalyticsEvents

### PR DESCRIPTION
**Pull request by Gouthamve**
Added schema based on existing events.
Added user now that we are giving even guests Ids
Modified Allow rule to check for valid insert.

Request for Review: @aaronjudd @spencern

### CODE REVIEW

**Comment by Gouthamve** [comment]
Now as I am trying to add userId to events recorded, I realised that Roles is an array and is given based on each shop.

I was thinking, because we have shopId and userId in the data, user.role is redundant.

**Comment by aaronjudd** [comment]
It's probably redundant, and because anonymous user accounts will likely be have some sort of garbage collection cleanup involved with them -> userId may not always be there to provide a later lookup, or a status either.  It might more useful to just add a boolean and track if  `isGuest = Roles.hasRoles(userId, 'anonymous', shopId) ` is true or not. that way there is some historical preservation / tracking of when a user converts from anon to guest.

**Comment by Gouthamve** [comment]
Some thing like this?

```
'user.id': {
    type: String,
    regEx: SimpleSchema.RegEx.Id,
    optional: true
  },
'user.isAnonymous': {
    type: Boolean,
    optional: true
},

```

**Comment by aaronjudd** [comment]
:+1:  make sense to me

**Pull request merged**
